### ISSUE TITLE
Dependency on Text::VisualWidth not declared

### ISSUE THREAD

**Issue by andk** [kaz-utashiro/Text-VisualPrintf#1]
http://search.cpan.org/grep?release=Text-VisualPrintf-2.01;string=Text::VisualWidth::PP;n=1;C=0

Mentioning in README.md is nice but does not count. It needs to appear in the machine-readable files of the toolchain.

Sample fail report: http://www.cpantesters.org/cpan/report/89358776

**Comment by kaz-utashiro** [comment]
Thank you.  It is declared in 'cpanfile', then 'META.json', but had a typo!

**Comment by kaz-utashiro** [comment]
Hmm... it seems "issue" was extra.
